language: python
sudo: required
python:
  - "3.4"
virtualenv:
  system_site_packages: true

install:
  - sudo apt-get install -y python3-pyqt4 python3-sip
  - pip install -r requirements.txt | cat

script:
  - nosetests

