language: python
sudo: required
python:
  - "3.6"
virtualenv:
  system_site_packages: false

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt | cat

script:
  - pytest tests

